### ISSUE TITLE
connecting to the hpc

### ISSUE THREAD

**Issue by JensTimmerman** [hpcugent/vsc_user_docs#123]
there should be a comment explaining that the first time you connect on a new machine, you should go to edit account, and follow the steps to create a ssh key again.

**Comment by boegel** [comment]
@redfast00 This is not fixed by #227 imho...

This is about how to add an additional SSH public key into your VSC account, which is what we recommend people to do when they want to connect from a new computer.

**Comment by redfast00** [comment]
I believe this has been fixed in #233, see https://github.com/hpcugent/vsc_user_docs/pull/233/files#diff-104eccde6b6deb39e1152d1015b5cbf7R73. Is this okay?
