### ISSUE TITLE
Minor rework to section 2.1.1 of Windows version (Install putty)

### ISSUE THREAD

**Issue by epauwels** [hpcugent/vsc_user_docs#125]
- Rename sectionhead "Install Putty" -> "Get Putty"
- Mention hard link to full path for Putty package
- All balletpoints below "The putty package consists of several components ..." can be deleted
- Add section on using bash (instead of putty) for Windows10 users

**Comment by JensTimmerman** [comment]
bash for windows 10 is not really recommended yet, you need to turn on developer mode, which I don't like recommending to our users, let's wait until it's easyier available

**Comment by boegel** [comment]
Yes, that's what I heard too.

I once did a quick try during a recent HPC-intro session, and we quickly ran into problems with SSH key permissions (basically everything was 777 :-|).

Somewhat unrelated, but a good measure of how mature the bash-on-Windows support is: https://github.com/hpcugent/easybuild-framework/issues/2072

**Comment by JensTimmerman** [comment]
Getting better thought: https://channel9.msdn.com/events/Windows/Windows-Developer-Day-Creators-Update/Developer-tools-and-updates#time=21m15s

**Comment by boegel** [comment]
@redfast00 Can you check whether built-in Linux shell support in Windows 10 is more mature now?
See https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by JensTimmerman** [comment]
It still needs you to enable developer mode, but it is supported and you can very easily install linux flavours from the microsoft app store once developer mode is turned on.

**Comment by boegel** [comment]
Let's follow up on the WSL aspect in #163.

@redfast00 Please check the other suggestions in this issue, can probably be fixed?

**Comment by boegel** [comment]
@redfast00 OK to close now?

**Comment by redfast00** [comment]
Yes please :+1:
