### ISSUE TITLE
remove unused glossary items from Linux intro

### ISSUE THREAD

**Issue by stdweird** [hpcugent/vsc_user_docs#151]
reading the first few pages of the ugent linux docs, there are quite a few gloassary items that seem to be part of the perfexpert docs, but the perferxpert docs seem to be missing from the ugent linux doc. if this is intentional, the corresponding (very technical) items should be removed.

also `last level cache` is abbreviated as `LLC`, not `LCC` (and there's inconsistent usage of `L1` vs `L1d` and friends in the perfexpert text).

**Comment by redfast00** [comment]
Yes
