### ISSUE TITLE
Makefile: minor problem when DOC is set

### ISSUE THREAD

**Issue by sbecuwe** [hpcugent/vsc_user_docs#154]
Example: make OS=linux SITE=antwerpen DOC=intro-HPC
will generate following two files, where only the first one should be generated

intro-HPC/intro-HPC-linux-antwerpen.pdf
intro-HPC/intro-HPC-antwerpen.pdf

To fix this problem following two lines probably need to be rewritten
DOCOS=$(DOC)
DOCNOOS=$(DOC)

**Comment by boegel** [comment]
@sbecuwe Was this fixed in #262?

**Comment by sbecuwe** [comment]
Yes. It seems I'm able now to select any combination of OS, SITE and DOC.
