### ISSUE TITLE
Remove macOS 3.2.3 section (Using a GUI)

### ISSUE THREAD

**Issue by alvarosimon** [hpcugent/vsc_user_docs#170]
It looks like the new MacOS versions do not support sftp protocol from the file browser GUI. URLs like this `sftp://vsc40000@login.hpc.ugent.be`    do not work from the GUI. 
This section should be removed.

**Comment by boegel** [comment]
Another option is to explain how to use `sshfs` instead: https://amaral.northwestern.edu/resources/guides/mounting-remote-folder-os-x-over-ssh-yosemite

**Comment by boegel** [comment]
@redfast00 Is this fixed in #261?

**Comment by redfast00** [comment]
@boegel yes, the filebrowser is now only suggested for Linux.
