### ISSUE TITLE
Update windows section 3.2.1 (WinSCP)

### ISSUE THREAD

**Issue by alvarosimon** [hpcugent/vsc_user_docs#172]
By default the new WinSCP version asks for the users `$HOME`  , if this value is not included WinSCP will user the root filesystem instead to show the available files. This is an issue if the user tries to perform a file search (magnifying glass icon). This will start a recursive search for all the available directories (with a performance impact in the used login node).

We should include this information in the current windows documentation to avoid this problem.

**Comment by boegel** [comment]
@redfast00 Please provide clear instructions on how to make sure that `$HOME` is properly defined in `WinSCP`.

**Comment by redfast00** [comment]
@boegel cyberduck is also available for Windows. Do we want to use that instead? Setup is really easy.

**Comment by boegel** [comment]
We tell people to use `WinSCP` in various places, I don't see a big reason to change that.

We can mention `CyberDuck` as an alternative though

**Comment by redfast00** [comment]
I could not reproduce this issue without changing settings: here's what the search menu looks like without any changes: 
![default](https://user-images.githubusercontent.com/10746993/45216783-06016180-b2a2-11e8-812b-ff70966806be.PNG)

That looks okay to me, but of course a user could change this to search through the entire server (but they could do the same with the `find` command).

I've checked, and WinSCP seems to set the remote directory as the home directory on the server.

**Comment by boegel** [comment]
According to https://winscp.net/forum/viewtopic.php?t=374 you can't even change what "home" is in WinSCP...

Closing then I guess, unless @alvarosimon has something to add here.

**Comment by alvarosimon** [comment]
probably it was fixed. I will close this one
