### ISSUE TITLE
Replace Xming software link in windows section 5.3.1

### ISSUE THREAD

**Issue by alvarosimon** [hpcugent/vsc_user_docs#173]
The link provided by the HPC windows documentation http://www.straightrunning.com/XmingNotes/
is not longer accessible. 
It should be replaced by a different software or link (maybe https://sourceforge.net/projects/xming/ )

**Comment by ngaro** [comment]
Works fine here. Probably a temporary glitch. I suggest keeping the straightrunning-link

**Comment by alvarosimon** [comment]
Yes is again up an running. I will close this issue.
