### ISSUE TITLE
quota section needs an update

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#177]
For HPC-UGent, it still mentions `show_quota`, which just tells users to visit https://account.vscentrum.be, so we should mention that directly.

What's the correct way to check quota for other sites?

@wpoely86 @hajgato @molden @gjbex @klust

**Comment by sbecuwe** [comment]
Users see their quota when logging in. See \else block in the Pre-defined quotas subsection in ch_running_jobs_with_input_output_data.tex.

**Comment by mselwa** [comment]
for KUL/UH:
quota -s (for $VSC_HOME and $VSC_DATA)
mmlsquota vol_ddn2:leuven_scratch --block-size auto (for $VSC_SCRATCH)
