### ISSUE TITLE
review/update documentation on copying files

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#191]
* see http://hpc.ugent.be/userwiki/index.php/User:VscCopy + http://hpc.ugent.be/userwiki/index.php/User:DataTransfer)
* check also what's documented in VSC website
  * https://www.vscentrum.be/client/windows/winscp
  * https://www.vscentrum.be/client/macosx/data-cyberduck
  * https://www.vscentrum.be/client/linux/data-openssh

**Comment by redfast00** [comment]
TODO: mention dos2unix?

**Comment by boegel** [comment]
@redfast00 Yes, doesn't hurt (of course under `\ifwindows`.

Isn't it mentioned anywhere in the documentation yet?

**Comment by redfast00** [comment]
Reminder: bccp?

**Comment by boegel** [comment]
@redfast00 I think you mean `bbcp` (see https://www.slac.stanford.edu/~abh/bbcp/).

`rsync` should definitely be documented properly, `bbcp` is a nice to have but (significantly) lower priority, mostly because it's not commonly available.

**Comment by redfast00** [comment]
@boegel Can this be closed? Everything in this issue is documented, except cyberduck (alternative mac file transfer program) and bbcp.

**Comment by boegel** [comment]
We should probably make an effort to document Cyberduck for macOS... I think Filezilla has been a PITA on macOS.

**Comment by redfast00** [comment]
In progress, see #261

**Comment by redfast00** [comment]
@boegel can this be closed? #261 has been merged.
