### ISSUE TITLE
review/update documentation on environment modules

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#192]
* see http://hpc.ugent.be/userwiki/index.php/User:VscModules (probably horribly outdated, see backup)
* https://www.vscentrum.be/cluster-doc/software/modules-lmod
  * more documented there than in VSC user manual, should be ported
* move from Chapter 3 to Chapter 4, since it's not related to Connecting to the HPC infrastructure
* whatever is specific to Lmod should be under `/ifgent`

**Comment by redfast00** [comment]
`ml save mycollection` stores the currently loaded modules to a collection
`ml restore mycollection` restores a previously stored collection of modules.

Do we want to add that to the manual?

**Comment by boegel** [comment]
Done in #273
