### ISSUE TITLE
troubleshooting: memory limits

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#195]
* see http://hpc.ugent.be/userwiki/index.php/User:Mem_limits
* memory limits that are in place on login nodes and in submitted jobs can manifest in different ways
  * `Out of memory` errors
  * segmentation faults & bus errors
  * `Could not allocate memory` errors
  * `Insufficient memory` errors
* explain how to check available memory (see `ulimit` output?)
* refer to relevant sections in manual, in particular how to request memory in jobs scripts
  * also check whether default is explained well, i.e. how much memory is requested by default b (probably specific to HPC-UGent?)
* Java-specific stuff can be added in a subsection, but should be moved out to software-specific part of documentation when it's in place

related issue: #126

**Comment by redfast00** [comment]
This has been done in #242 and there's a separate issue for java stuff, can this be closed?
