### ISSUE TITLE
software-specific: EasyBuild

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#199]
* add chapter in Part III (see #196) how users can install software in their own account using EasyBuild
* see http://hpc.ugent.be/userwiki/index.php/User:EasyBuild
* make sure it's clear when (not) to do this
  * refer to section explaining how to request central software installations (cfr. #187)

**Comment by redfast00** [comment]
@boegel can you please close this issue?

**Comment by boegel** [comment]
fixed in #311
