### ISSUE TITLE
add "FAQ" chapter to Part I

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#202]
* When will my job start?
  * see https://www.vscentrum.be/cluster-doc/running-jobs/submitting-managing-jobs#getting-an-estimate-for-the-start-time-of-your-job:-showstart?
  * `showstart` is not available in HPC-UGent infrastructure
  * briefly explain how job scheduler works (cfr. #187)

* Can I share my account with someone else?
  * short but firm answer: NO!
  * see http://helpdesk.ugent.be/account/en/regels.php for UGent, equivalent for other sites?
  * mention alternatives, e.g. shared directory in VO space

* Can I share my data with other HPC users?
  * now a one-liner on chmod, should be replaced by proper documentation on this

* I no longer work for UGent. Can I transfer my data on the HPC to another researcher working at Ghent University?
  * can be replaced with pointer to data policy (accountpage?)

**Comment by boegel** [comment]
@redfast00 I don't think this should be a Ghent specific chapter, some parts will certainly be relevant to other sites as well (like the general concept of not being allowed to share accounts, sharing of data via a shared directory, not being able to accurately predict when a job will start, etc.).

Create a new chapter, and wrap the parts that are specific to Ghent in `\ifgent`, other sites can pitch in with more details beyond the general answer.

**Comment by redfast00** [comment]
And I don't really get "can be replaced with pointer to data policy (accountpage?)" What data policy?

**Comment by boegel** [comment]
@redfast00 Add a section in HPC-intro that gives a specific example on how to use `chmod` & co to set up a directory that can be shared with others. Other stuff comes into play too, like groups (cfr. #194).

In the Linux-intro, keep the general `chmod` info and refer to the HPC-intro section for details on how to set up a shared dir. We shouldn't explain `chmod` in detail in the HPC-intro document imho, that's basic Linux. In this case, I think it makes sense to refer to the Linux intro from the HPC-intro in case they want more info on `chmod`.

**Comment by boegel** [comment]
@redfast00 Forget about the data policy thing for now, we'll discuss that later. Tackle the other stuff, and then maybe open an dedicated issue for that last bullet.
