### ISSUE TITLE
document how to kill running processes/jobs

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#204]
* http://hpc.ugent.be/userwiki/index.php/User:KillJobProcess
* `ps` + `kill` for processes (e.g. on login nodes)
* `qdel` for jobs
* also mention how to prevent data loss by reaching walltime limit (in a proper way...)

**Comment by redfast00** [comment]
- `qdel` is documented in ch_running_batch_jobs.tex
- `ps` and `kill` are documented in the Linux-intro. Should we cross-reference? If so, from where?

**Comment by boegel** [comment]
That's probably good enough... The only thing missing then is an example of how to copy data out before the job is killed because running into walltime?

**Comment by redfast00** [comment]
See #306 :)
