### ISSUE TITLE
fix long build/test times in Travis

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#215]
* Travis jobs testing PRs (+ `master` on merges) now take a very long time, and sometimes fail because of crossing the 1h time limit
  * see for example https://travis-ci.org/hpcugent/vsc_user_docs/builds/421043323
  * `./install-tl -profile $TRAVIS_BUILD_DIR/texlive.profile` takes over 2600s...
* options to try:
  * use Travis cache rather than reinstalling every time (see https://docs.travis-ci.com/user/caching/)
  * use more recent Ubuntu image in Travis + install straight from Ubuntu repos

**Comment by boegel** [comment]
@wpoely86 Anything to add here?

**Comment by wpoely86** [comment]
I did the whole thing with the `install-tl` because at the time the travis image was still Ubuntu 12.04 and it had a very old LaTeX. 

The easiest thing to try it simple swap it for one of the newer travis images and use the repo provided LaTeX packages.
