### ISSUE TITLE
ECDSA fingerprint instead of RSA

### ISSUE THREAD

**Issue by redfast00** [hpcugent/vsc_user_docs#222]
```
The authenticity of host 'login.hpc.ugent.be (157.193.16.9)' can't be established.
ECDSA key fingerprint is SHA256:1MNKFTfl1T9sm6tTWAo4sn7zyEfiWFLKbk/mlT+7S5s.
Are you sure you want to continue connecting (yes/no)?
```

**Comment by boegel** [comment]
@redfast00 Can you clarify? Are the docs only mentioning RSA fingerprints? If so, where exactly?

**Comment by redfast00** [comment]
It seems that we're including all fingerprints, even though our users will only see one of them. They also don't get rendered optimally. I overlooked that there was even an ECDSA SHA256 fingerprint. It's not that high priority (I should have read it better), but the output isn't what users will see.

**Comment by boegel** [comment]
That's probably because that has been changing over time. Also PuTTy may be showing other fingerprints?
