### ISSUE TITLE
troubleshooting: permission denied when logging in

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#232]
Quite a few users run into this problem when first connecting to their account. Likely causes (in order of how frequently they occur, more or less)

* trying to connect too soon, it takes a while before a freshly approved VSC account is fully active (login should work no longer than 1 hour after account approval)
* SSH private key is not in default location on Linux or macOS (i.e. $HOME/.ssh/id_rsa)
  * in this case, there are several options: `ssh -i` (mentioned now in section 3.1.1)
  * add to SSH agent (`ssh-add`); already documented, but under `/iflinux` while it also works for macOS
  * specify location (username + hostname) in SSH configuration (`$HOME/.ssh/config`)
* from VSC login ID (typo?)
   * suggest to doube/triple check, see https://account.vscentrum.be/, and tell them what to look for (starts with `vsc`, followed by exactly 5 digits)
* matching (additional) SSH pubkey is not uploaded to VSC account yet (cfr. #123)
   * also needs some time to become active (max 15-20min)
* provide location of SSH pubkey rather than private key to PuTTy or `ssh` command
* using the incorrect SSH private key
  * provide some guidelines on how to check whether correct private key is used (and clearly mention never to share the private key with anyone, as a reminder...)

An extensive section on this should be added to the Troubleshooting chapter, and referred to from Chapter 3 in case any problems occur when trying to connect.

**Comment by boegel** [comment]
If all else fails, suggest them to contact support and to provide the output of `ssh -vvv` (macOS or Linux), or PuTTy log info (you'll have to figure out how to get that, there *is* a way I think...).

**Comment by redfast00** [comment]
This has been done in #233. @boegel can you please close this?
