### ISSUE TITLE
documentation on VOs

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#236]
* see http://hpc.ugent.be/userwiki/index.php/User:VSCVos
* how to request new VO
* how to join existing VO
* relation to storage quota
* all specific to UGent, so under `\ifgent`
* new section 6.6?
* should also cover `$VSC_DATA_VO`, `$VSC_DATA_VO_USER` (+ difference with `$VSC_DATA`)

**Comment by boegel** [comment]
@redfast00 This one can be closed now I think?

**Comment by redfast00** [comment]
Yup, indeed.
