### ISSUE TITLE
Collect URLs from other institutions linking to their rules about sharing accounts.

### ISSUE THREAD

**Issue by redfast00** [hpcugent/vsc_user_docs#243]
See #229

**Comment by boegel** [comment]
@wpoely86, @klust, @gjbex, @mselwa Can you provide the correct URL to the university rules that mention not to share accounts?

**Comment by mselwa** [comment]
For KU Leuven
https://admin.kuleuven.be/personeel/english_hrdepartment/ICT-codeofconduct-staff#section-5

**Comment by wpoely86** [comment]
VUB: http://www.vub.ac.be/sites/vub/files/reglement-gebruik-ict-infrastructuur.pdf

**Comment by sbecuwe** [comment]
UAntwerpen: https://pintra.uantwerpen.be/bbcswebdav/xid-23610_1

**Comment by gjbex** [comment]
For UHasselt:
https://www.uhasselt.be/intra/IVC

**Comment by boegel** [comment]
@redfast00 Please mention that URL in the relevant location under `\ifleuven` (since there's no UHasselt specific version of the PDF), and clarify which link is for KU Leuven, which for Hasselt University

**Comment by redfast00** [comment]
All institutions are now in the docs.
