### ISSUE TITLE
How do users know when their job will start?

### ISSUE THREAD

**Issue by redfast00** [hpcugent/vsc_user_docs#246]
See #229: currently, there is a question "When will my job start?" that is wrapped in an `\ifgent`. In Ghent, we don't have the `showstart` command, how about other institutions?

**Comment by boegel** [comment]
Already covered for VUB via #244

At KUL they do provide `showstart`. Not sure about UA (@klust, @backelj?)

**Comment by backelj** [comment]
We do.

Op 3 sep. 2018, om 09:28 heeft Kenneth Hoste <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Already covered for VUB via #244<https://github.com/hpcugent/vsc_user_docs/pull/244>

At KUL they do provide showstart. Not sure about UA (@klust<https://github.com/klust>, @backelj<https://github.com/backelj>?)

**Comment by boegel** [comment]
@redfast00 Please re-check whether current info is correct for all sites?
