### ISSUE TITLE
Errors when using macro's at end of line

### ISSUE THREAD

**Issue by redfast00** [hpcugent/vsc_user_docs#266]
When using the `\hpc` macro at the end of a line, this error is produced.

```
./intro-HPC.tex:92: Incomplete \iffalse; all text was ignored after line 1.
<inserted text> 
                \fi 
l.92 \include{ch_quick_reference_guide}
                                       
./intro-HPC.tex:92:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on intro-HPC-linux-gent.log.
```
When the `\xspace` command is removed from the `\macro` newcommand in `macros.tex`, this error doesn't appear anymore, but the space at the end also doesn't.

**Comment by sbecuwe** [comment]
Not able to reproduce it. Could you post or mail a minimal working/breaking example?

**Comment by redfast00** [comment]
@sbecuwe not minimal, but https://github.com/hpcugent/vsc_user_docs/pull/287/files currently (f86885af16b648a3c724a1bdfa04bc3f76083c2c) doesn't build. When I remove or comment out [line 164](https://github.com/hpcugent/vsc_user_docs/pull/287/files#diff-17420a9f0fde9c41bc388754113d78d6R164), it does build.

**Comment by sbecuwe** [comment]
Trouble is caused by a macro in a chapter title: \chapter{\hpc Quick Reference Guide}
Chapter definitions are rather complex constructions. Together with the \macro, it seems to go wrong.
Didn't figure out yet how to change the \macro. 
Suggestion: just write \chapter{HPC Quick Reference Guide}, since other chapters also have HPC in their title ...

**Comment by redfast00** [comment]
Thank you @sbecuwe, that seems to have helped. The `\xspace` in the `\macro` definition has caused problems in the past, maybe it's that?

**Comment by redfast00** [comment]
This was indeed fixed by removing `\hpc` from the chapter.
