### ISSUE TITLE
\verb overflows out of the page

### ISSUE THREAD

**Issue by redfast00** [hpcugent/vsc_user_docs#278]

**Comment by redfast00** [comment]
`\lstinline` is the solution, now for a global sed across the entire repo

**Comment by redfast00** [comment]
`sed -E 's/verb\|([^|]*)\|/lstinline|\1|/g'`

**Comment by boegel** [comment]
Any references to `\verb` vs `\lstinline`?

**Comment by redfast00** [comment]
@boegel didn't find anything, but I've tested it: `verb` overflows outside of the page, where `lstinline` breaks at spaces if needed.

Closing since PR got merged.
