### ISSUE TITLE
look into building with MiKTeX

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#281]
@redfast00 Please look how much work it would be to build with MiKTeX (https://miktex.org) rather than TeXLive.

This would probably involve not use some of the 'exotic' packages we rely on now...

Also try and figure out how you build the documentation with using `make` (i.e. how to pass down the OS & SITE variable using MiKTeX).

cc @mselwa, @gjbex

**Comment by redfast00** [comment]
I just succesfully built a PDF on Windows 🎉

Steps taken:

1. Install MiKTeX and Strawberry Perl
2. In MiKTeX console, install  the `latexmk` package
3. Open `intro-Linux/intro-Linux.tex` in TeXworks (MiKTeX' editor) and press the green "play" button. This won't actually succesfully compile, but will prompt to install all the packages we need. Click "Yes" for all packages.
3. Build a pdf with this command: `latexmk -pdf -verbose -r ../latexmkrc -jobname="intro-Linux-windows-gent" -pdflatex="pdflatex -halt-on-error --file-line-error %O \"\def\iswindows{1}\def\isgent{1}\input{%S}\" " intro-Linux.tex`

I realize this isn't userfriendly (especially the last step), but I could write a small script that the user would just have to doubleclick and fill in the details in a dialog (linux, gent).

@boegel what's your opinion on this?

**Comment by boegel** [comment]
@redfast00 This looks doable, but I'd really like to hear from @mselwa and maybe also @gjbex on this.

A couple more things:

* We should create a `*.bat` script to avoid having to use that command on Windows, ideally one that accepts two arguments (the value for OS & SITE), and maybe also one that builds the documentation for all OSs/SITEs (equivalent with `make all`).
* We should add a section in the README that explains how to compile the documentation on Windows, which also mentions that no admin rights are needed to install what is required.

@mselwa Can you give this a try and let us know how it works out for you?

Some cleanup w.r.t. required packages is done in #285, so it probably makes sense to wait until that PR is merged.

**Comment by boegel** [comment]
@redfast00 Please look into adding a `.bat` script that works on Windows, and extend the `README` to explain how to use it (and to document the procedure for setting up MikTeX).

**Comment by boegel** [comment]
fixed in #296
