### ISSUE TITLE
Add section "How to get system info"

### ISSUE THREAD

**Issue by redfast00** [hpcugent/vsc_user_docs#299]
- Insert before submitting a job script in chapter 4
- ifgent: document pbsmon, hpc.ugent.be/clusterstate
- does VUB have pbsmon?
- general: https://www.vscentrum.be/en/user-portal/system-status, qstat -q, http://hpc.ugent.be/userwiki/index.php/User:VscSystemInfo

**Comment by boegel** [comment]
@wpoely86 Does VUB have `pbsmon`?

**Comment by wpoely86** [comment]
not yet. We have something called `nodestat` which does something similar.
