### ISSUE TITLE
documentation refers to $VSC_SCRATCH_LOCAL which is not available

### ISSUE THREAD

**Issue by wdpypere** [hpcugent/vsc_user_docs#324]
in 11.5.1 Monitoring File sizes during execution there is a reference to  `$VSC_SCRATCH_LOCAL` which is not available in my env.
```
 -bash-4.2$ env | grep VSC_SCRATCH_LOCAL
```
It should probably be `$VSC_SCRATCH_NODE`
```
-bash-4.2$ env | grep VSC_SCRATCH_NODE 
VSC_SCRATCH_NODE=/local
```

**Comment by boegel** [comment]
fixed in #325
