### ISSUE TITLE
[tier1-cloud] create and setup adhoc VM images

### ISSUE THREAD

**Issue by alvarosimon** [hpcugent/vsc_user_docs#331]
from Alexander Botzki email

> I am approaching you to ask whether you would be able to meet to discuss the 
> conceptual setup of our project early next year.
> 
> What would be the preferred way of implementing the software configuration on 
> the server: see 
> https://docs.openstack.org/heat/rocky/template_guide/software_deployment.html?
> 
> At the moment, to build an image of a training server costs us 1 hour (ansible 
> script) on GCE since many command line tools are installed and several R 
> packages have to be compiled.
> As far as I see on GCE there is the option to export an image to qcow2. This 
> seems a shortterm solution, though.
> 
> So, any feedback would be appreciated.
> 
> Cheers,
> 
> Alex

**Comment by abotzki** [comment]
thanks for the feedback, on a genral note I was wondering what you suggest to setup the 'machine' which talks with OpenStack.
I've identified several examples where OpenStack servers are setup via a (virtual) linux box where e.g ansible is installed. For this to work you need to download the openrc.sh file (with keys etc) on this box and then you can ssh to the OpenStack server where the Heat template is run.
Is VPN to UGent sufficient to get this working or do you have to be on an HPC node?

Furthermore, I am wondering whether in the future you anticipate to use OS::Heat::SoftwareConfig

Thanks for your feedback.

**Comment by stdweird** [comment]
@abotzki 
* to reach the APIs, no vpn is needed (or should be; if it is, it's a bug and we will fix it)
* to reach your public IPs, the default rule is only access from the gent loginnode. if you need anything else, ask us and we will change it. (the default rule is there because we cannot set everything open by default)

**Comment by alvarosimon** [comment]
@abotzki 
About the new openstack release, after the openstack upgrade we are testing the application credential setup. I did some tests from my laptop, you need the latest openstack client (rocky) and the terena CA in your machine  (required for the ssl handshake) to connect to the API (you should generate a valid app token  from the dashboard first). It works for a "regular" user but not for a vsc user.. I'm taking a look to this. (and yes we will create the new project for you soon :smile:  )
