### ISSUE TITLE
[tier1-cloud] include application credential documentation

### ISSUE THREAD

**Issue by alvarosimon** [hpcugent/vsc_user_docs#332]
This is available since Rocky release. It is useful for advance users that want to generate their own tokens and credentials from the dashboard. They can use these tokens to connect directly to the OpenStack public endpoints https://cloud.vscentrum.be/dashboard/project/api_access/

 * They should access to https://cloud.vscentrum.be/dashboard/identity/application_credentials/ to genate/download the new credential to use the clients.

* Also they should download the latest OS clients:
https://docs.openstack.org/newton/user-guide/common/cli-install-openstack-command-line-clients.html

More information about the app credentials here:
https://docs.openstack.org/keystone/rocky/user/application_credentials.html

**Comment by alvarosimon** [comment]
I forgot to say, we should include this info in the documentation as well. They need the Terena CA certificate to connect to the SSL endpoint and set `REQUESTS_CA_BUNDLE`
like this:

`export REQUESTS_CA_BUNDLE=$HOME/terena-bundle.pem
`

Maybe we should install the clients in the current HPC login nodes

**Comment by stdweird** [comment]
@alvarosimon also document where users can download the CA bundle.
for the loginnodes, the variable should 
* either exist
* identical (profile?) script be avaialble, so users can source it
* CA located on the same path everywhere, so we can document it

**Comment by alvarosimon** [comment]
ok I found this one chain CA3 for TERENA CA that is works:
https://pki.cesnet.cz/certs/chain_TERENA_SSL_CA_3.pem

**Comment by stdweird** [comment]
is that the official location for the CA certs?

**Comment by alvarosimon** [comment]
@stdweird no, that's from cesnet web page. It's a bit stupid but I didn't find the ca bundle from terena web page...

**Comment by stdweird** [comment]
@alvarosimon if you can't find it, mail geant support, they are supposed to host it

**Comment by alvarosimon** [comment]
@stdweird ok I will ask to geant. 
Iin our case the CA bundle is already available from the login nodes and os machines in `/etc/pki/CA/certs/terena-bundle.pem`    
We can modify the openrc.sh template provided by the dashboard in `/usr/share/openstack-dashboard/openstack_dashboard/dashboards/identity/application_credentials/templates/application_credentials/openrc.sh.template`   to setup this variable automatically but the users should change this path if they are using their own computer.

**Comment by stdweird** [comment]
actaully we should try to fix it. i probably found some way to fix it permanently. remind me to test this :smile:

**Comment by stdweird** [comment]
for the apis behind apache, we should set `SSLCertificateChainFile` option in the vhosts
for nginx (and some others, we have to use the certificate+chain as certificate).

**Comment by stdweird** [comment]
to verify, use `openssl s_client -connect cloud.vscentrum.be:apiport`

**Comment by stdweird** [comment]
as the terena ca certs are signed by digicert root, there should be no need to specify the ca cert i think

**Comment by alvarosimon** [comment]
@stdweird ah ok, right now from our nginx conf we have this for the endpoints:
`ssl_certificate /etc/pki/tls/certs/cert-cloud.vscentrum.be.pem;`
but this does not include the CA bundle.
