### ISSUE TITLE
X2Go private key issue on Windows

### ISSUE THREAD

**Issue by hajgato** [hpcugent/vsc_user_docs#335]
Linux (RHEL7 and Co.) generated private keys are not understood by X2Go (it prompts for a passphrase indpepndetly whether the key is passphrase protected or not). 

The soution is either to use pageant (using windows style .ppk format), or convert the private key to "older" format (like it was in RHEL6 and Co.) using puttygen. (conversions -> export SSH key), but do not use the force new format.

X2Go does not understand windows style (.ppk) key format.

The background:
The new format uses a header (someting like openssh-key-v1nonenonessh-rsa in the base64 encoded key, the old format strictly have the key). 

I have no idea wether the MacOS or the Linux versions are also work the same way.

**Comment by boegel** [comment]
Looks like this changed in `OpenSSH` 7.8, cfr. https://www.openssh.com/releasenotes.html

```
ssh-keygen(1): write OpenSSH format private keys by default
   instead of using OpenSSL's PEM format. The OpenSSH format,
   supported in OpenSSH releases since 2014 and described in the
   PROTOCOL.key file in the source distribution, offers substantially
   better protection against offline password guessing and supports
   key comments in private keys. If necessary, it is possible to write
   old PEM-style keys by adding "-m PEM" to ssh-keygen's arguments
   when generating or updating a key.
```
