### ISSUE TITLE
Add link to intro-Cloud on github pages

### ISSUE THREAD

**Issue by tdanckaert** [hpcugent/vsc_user_docs#337]
The page http://hpcugent.github.io/vsc_user_docs/index.html does not link to the new VSC cloud tutorial "pdf/intro-Cloud.pdf".  The following change to index.html should fix that

https://github.com/tdanckaert/vsc_user_docs/commit/16b956f1134c3cdaa1c510fd2d5a2604ecf8e1b1

but I'm not sure how this can be published to github pages.

**Comment by stdweird** [comment]
@gjbex @boegel @klust any ideas?

**Comment by boegel** [comment]
@wpoely86 Is the expert here.

That commit should be added to the `gh-pages` branch (via a pull request)?

**Comment by tdanckaert** [comment]
It seems the gh-pages branch is recreated every time the pages are updated (it always contains a single commit, the current one is from 21 hours ago, after the last merge to master).

**Comment by wpoely86** [comment]
The `deploy.sh` has all the magic. The `gh-pages` branch is indeed force-pushed on every merge in master.

To change anything in `index.html` you need to do a PR to the `gh-pages` directly. It will get overwritten after merge but with the change.
I'm not sure why I did it like that, maybe it's easier to just add the `index.html` in the master branch?

**Comment by tdanckaert** [comment]
Ah ok, now I understand.  I've rebased on top of the new gh-pages branch, and made a pull request.

> maybe it's easier to just add the index.html in the master branch?

Yes, that would be easier.  The current procedure is a bit weird.

**Comment by boegel** [comment]
@wpoely86 I think we do the force push to avoid that we keep all the PDFs in git history...

**Comment by wpoely86** [comment]
The force push is unavoidable but also no issue IMHO.

But the thing with the `index.html` is weird. I've got no clue why I did it like that.
