### ISSUE TITLE
[UGent] remove/replace Singularity hub link in chapter 24

### ISSUE THREAD

**Issue by alvarosimon** [hpcugent/vsc_user_docs#373]
This link https://singularity-hub.org/  is no longer valid or is not working properly.

**Comment by hajgato** [comment]
https://singularityhub.github.io/singularityhub-docs/2021/going-read-only/
Se the text should be rephrased, there will be no singularity repo in the near future

**Comment by hajgato** [comment]
see: https://github.com/hpcugent/vsc_user_docs/pull/426
