### ISSUE TITLE
Issues with loading a module in the PBS scripts

### ISSUE THREAD

**Issue by fg-personal** [hpcugent/vsc_user_docs#440]
To whom it may regard,

I want to use a module available in Easybuild but I am getting this error

>` Lmod has detected the following error: The following module(s) are unknown:
> "MODULENAME"
> 
> 
> Please check the spelling or version number. Also try "module spider ..."
> It is also possible your cache file is out-of-date; it may help to try:
> $ module --ignore-cache load "MODULENAME"
> 
> 
> Also make sure that all modulefiles written in TCL start with the string
> #%Module
> 
> 
> If you don't understand the warning or error, contact the helpdesk at
> hpc@ugent.be
> 
> 
> 
> /var/spool/slurm/slurmd/jobXXXXXX/slurm_script: line 36: /bin/MODULENAME: No such file or directory`
> 

I have no issues with loading it in the command line

> `[vscXXXXX@gligar05 ~]$ module swap cluster/skitty
> 
> 
> We advise you to log in to a RHEL 8 login node when using the skitty cluster.
> 
> 
> The skitty cluster is using RHEL 8 as operating system,
> while the login node you are logged in to is using CentOS 7.
> 
> 
> To avoid problems with testing installed software or submitting jobs,
> it is recommended to switch to a RHEL 8 login node by running 'ssh login8'.
> 
> [vscXXXXX@gligar05 ~]$ module use $VSC_DATA_VO/easybuild/$VSC_OS_LOCAL/$VSC_ARCH_LOCAL$VSC_ARCH_SUFFIX/modules/all
> [vscXXXXX@gligar05 ~]$ module load MODULENAME
> [vscXXXXX@gligar05 ~]$ module unload MODULENAME`

What should I do? The script I am qsub-ing is something like this:

> `#PBS -N "MyQSUB"
> #PBS -l walltime=0X:00:00
> #PBS -l nodes=1:ppn=X
> #PBS -l vmem=XXXXm
> #PBS -m abe
> module use $VSC_DATA_VO/easybuild/$VSC_OS_LOCAL/$VSC_ARCH_LOCAL$VSC_ARCH_SUFFIX/modules/all
> module load MODULENAME
> export program= MODULEPATH
> 
> ${program} ...`

**Comment by stdweird** [comment]
please send an email to `hpc@ugent.be` for support questions like this
