### ISSUE TITLE
Fix some newline whitespaces and formatting from Connecting Linux/Mac sections

### ISSUE THREAD

**Issue by alvarosimon** [hpcugent/vsc_user_docs#487]
A minor issue, it only affects to Linux and MacOS mds:

https://docs.hpc.ugent.be/macOS/connecting/#transfer-files-tofrom-the-hpc

https://docs.hpc.ugent.be/Linux/connecting/#transfer-files-tofrom-the-hpc

**Comment by stdweird** [comment]
@alvarosimon what is this about? (if you make PRs do it on top of #489 or wait till it is merged)

**Comment by alvarosimon** [comment]
@stdweird the formatting issue is still there, from the first link you can see it at the beginning of this paragraph and below:
```
The scp command can also be used to copy files from the cluster to your local machine. Let us copy the remote file "intro-HPC-macOS-Gent.pdf" from your "docs" subdirectory on the cluster to your local computer
....
```
I can try to fix it in a new PR..
