### ISSUE TITLE
detect build failure

### ISSUE THREAD

**Issue by stdweird** [hpcugent/vsc_user_docs#497]
somehow, we miss build failures like #496

**Comment by boegel** [comment]
The problem is that the `build.py` script flat out ignores the exit code of the `mkdocs build` commands being run, I think...

**Comment by stdweird** [comment]
we could at least parse the output of mkdocs to see if it spits some garbage out

**Comment by stdweird** [comment]
#498 runs mkdocs in strict, any warning already fails the build
