### ISSUE TITLE
Tutorial for running programs which is out of walltime continuous

### ISSUE THREAD

**Issue by She1111** [hpcugent/vsc_user_docs#500]
Hi,

I have a huge data to analysis and it will take long time (out of limited 72 hours walltime). I would like to run the programs continuous. Could you please give me some advice to do that? The software is DIA-NN/1.8.1 https://github.com/vdemichev/DiaNN
Thank you very much and I am looking forward to your reply!

Best regards,
Shel

**Comment by boegel** [comment]
This is not the right platform for getting support, please contact us via the usual email address, see https://www.ugent.be/hpc/en/support
