### ISSUE TITLE
search does not find words in code part of the docs

### ISSUE THREAD

**Issue by hajgato** [hpcugent/vsc_user_docs#501]
docs do not search in codes, for example no ARCANINE found at all, but it is in the docs: https://docs.hpc.ugent.be/Linux/running_jobs_with_input_output_data/#where-to-store-your-data-on-the-hpc

**Comment by alvarosimon** [comment]
actually I was wrong, it does the search, it works with any word, but it does not highlights it due to the underscore `_`
