### ISSUE TITLE
document workaround for `Illegal instruction` problem when using `wsub` (worker)

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#535]
A common problem we get questions about on a regular basis is running into an `Illegal instruction` error when trying to submit a worker job:

```
[vsc40000@gligar08 ~]$ wsub
/apps/gent/RHEL8/skylake-ib/software/worker/1.6.12-foss-2021b/bin/wsub: line 27: 488851 Illegal instruction     (core dumped) ${PERL} ${DIR}/../lib/wsub.pl "$@"
```

We should document the workaround we have in place for this (use `module swap env/slurm/skitty` rather than `module swap cluster/skitty`). 
This should be done in https://docs.hpc.ugent.be/multi_job_submission/, but a pointer should be added from the troubleshooting section we have on the `Illegal instruction` problem (https://docs.hpc.ugent.be/troubleshooting/#running-software-that-is-incompatible-with-host).
We should maybe also make that last section a bit easier to find, by using a better subsection title (that includes `Illegal instruction`).

Example tickets that provide more info:
* https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=121096
* https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=126530

**Comment by milachae** [comment]
I will add this to the docs
