### ISSUE TITLE
Instant loading  is broken

### ISSUE THREAD

**Issue by xerbalind** [hpcugent/vsc_user_docs#543]
While exploring the website,  each time you navigate through the side menu or table of contents, the page undergoes a complete reload.

Within the code,  two types of markdown links exist:

```md
[link](../link)
```
OR

```md
[link](link.md)
```

The latter choice is significantly **preferred**.

When clicking a link from either option, the page loads instantly as anticipated. However, only after clicking on the the second type of link, from now on, when you navigate via the menu on the left, the page loads instantly (better). With the first link type the complete reloading issue persists.

I think it's something to do with os pick redirection

**Comment by boegel** [comment]
Re-opening to get some feedback from @stdweird, but as far as we can tell removing the code in #547 doesn't cause trouble

**Comment by xerbalind** [comment]
> Re-opening to get some feedback from @stdweird, but as far as we can tell removing the code in #547 doesn't cause trouble

It seems removing the code caused this problem: #558
