### ISSUE TITLE
Hardcoded urls in linux tutorial

### ISSUE THREAD

**Issue by xerbalind** [hpcugent/vsc_user_docs#545]
Example: 

https://github.com/hpcugent/vsc_user_docs/blob/bf6caaaca36ac6c48205a6f8890f07e2a888458f/mkdocs/docs/HPC/only/gent/linux-tutorial/getting_started.md?plain=1#L8

This is because linux-tutorial is in 2 places: under mkdocs/docs/HPC/only/gent and mkdocs/docs as symlink.

This issue can be solved by placing it under one location.

**Comment by boegel** [comment]
@stdweird Do you recall why we parked the Linux tutorial under `mkdocs/docs/HPC/only/gent` + symlink from `mkdocs/linux-tutorial`?

If there was no particular reason, or we don't know, we can just move it under `mkdocs/Linux-tutorial` and drop the symlink.

The only reason I can think of it that there may be UGent-isms in there (@xerbalind can you check if that's the case or not?).
If so, we can deal with that via the templates or by using conditional parts?

**Comment by boegel** [comment]
@xerbalind Can you look into that? Basically comes down to removing the symlink and moving stuff from `mkdocs/docs/HPC/only/gent/linux-tutorial` to `mkdocs/linux-tutorial`, plus perhaps some cleanup (like removing the hardcoded URLs).

**Comment by xerbalind** [comment]
Fixed in #557
