### ISSUE TITLE
wrong link to localhost

### ISSUE THREAD

**Issue by hajgato** [hpcugent/vsc_user_docs#590]
Issue description:
A link on the web version redirects to a localhost address.

The issue is located at:

    Connecting to the HPC infrastructure
        Transfer files to/from the HPC
            Using scp
            the chapter titled "Uploading/downloading/editing files", section "Symlinks for data/scratch" in the intro to Linux
            -->  This link redirects to localhost:8000/Gent/macOS/intro-Linux/uploading_files/#symlinks-for-datascratch

Instead it should link to:
https://docs.hpc.ugent.be/Linux/linux-tutorial/uploading_files/?h=symlinks#symlinks-for-datascratch
(Linux)

https://docs.hpc.ugent.be/macOS/linux-tutorial/uploading_files/?h=symlinks#symlinks-for-datascratch

see: https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=139332

**Comment by lbarraga** [comment]
See #674 for a list of this and other broken links

**Comment by boegel** [comment]
@lbarraga fixed with #696
