### ISSUE TITLE
update examples/output with ancient modules

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc_user_docs#671]
We have a couple of places in the documentation where we're showing/using very old module names, which are not available anymore (or won't be very soon).

@lbarraga Can you take a look at hunting those down, and trying to update them?

In general, aim for using modules that use a toolchain `*/2023a` or newer (or a subtoolchain thereof).

If you grep for `GCC-`, `GCCcore-`, `-201`, and `-202[012]` you should be able to find most of them (do ignore the `available_software` subdirectory, since the tables in there are auto-generated)

**Comment by lbarraga** [comment]
Ok, I will look into this
