### ISSUE TITLE
Problems with links

### ISSUE THREAD

**Issue by EwDa291** [hpcugent/vsc_user_docs#674]
Some links in the documentation lead to pages that don't exist. Right now the ones I have been able to locate are:

alphafold.md:
[localhost](https://github.com/hpcugent/vsc_user_docs/blob/1da87a6efe5540fc9d45c1072b2d1468bc60be8c/mkdocs/docs/HPC/alphafold.md?plain=1#L81)
[typo in the link](https://github.com/hpcugent/vsc_user_docs/blob/1da87a6efe5540fc9d45c1072b2d1468bc60be8c/mkdocs/docs/HPC/alphafold.md?plain=1#L134)
[typo in the link](https://github.com/hpcugent/vsc_user_docs/blob/1da87a6efe5540fc9d45c1072b2d1468bc60be8c/mkdocs/docs/HPC/alphafold.md?plain=1#L159)
[typo in the link](https://github.com/hpcugent/vsc_user_docs/blob/1da87a6efe5540fc9d45c1072b2d1468bc60be8c/mkdocs/docs/HPC/alphafold.md?plain=1#L159)

LinuxManualURL.md
[localhost](https://github.com/hpcugent/vsc_user_docs/blob/1da87a6efe5540fc9d45c1072b2d1468bc60be8c/mkdocs/docs/HPC/macros/LinuxManualURL.md?plain=1#L3)

There are also some links that work in the documentation, but don't when copy-pasting them in a browser:

common_pitfalls.md
[Both links on this line](https://github.com/hpcugent/vsc_user_docs/blob/1da87a6efe5540fc9d45c1072b2d1468bc60be8c/mkdocs/docs/HPC/linux-tutorial/common_pitfalls.md?plain=1#L140)

**Comment by lbarraga** [comment]
The `typo in link` refers to the link not having the `.md`  extension

**Comment by lbarraga** [comment]
Additional broken links:

## Site does not exist

- http://wikki.gridcore.se/foam-extend ([line](https://github.com/hpcugent/vsc_user_docs/blob/4c4002f424ab99ffcfbedb678c84cd50d38a5907/mkdocs/docs/HPC/openFOAM.md?plain=1#L22))

## 404 Not Found

- http://www.prace-ri.eu/IMG/pdf/IO-profiling_with_Darshan-2.pdf: ([line](https://github.com/hpcugent/vsc_user_docs/blame/4c4002f424ab99ffcfbedb678c84cd50d38a5907/mkdocs/docs/HPC/openFOAM.md#L287))
- http://www.vub.ac.be/sites/vub/files/reglement-gebruik-ict-infrastructuur.pdf: ([line](https://github.com/hpcugent/vsc_user_docs/blob/4c4002f424ab99ffcfbedb678c84cd50d38a5907/mkdocs/docs/HPC/FAQ.md?plain=1#L269))

**Comment by lbarraga** [comment]
See PR #696 to avoid new and detect old faulty links

**Comment by boegel** [comment]
fixed in #696
