### ISSUE TITLE
\ifmac + \iflinux

### ISSUE THREAD

**Issue by GeertBorstlap** [hpcugent/vsc_user_docs#69]
We use \ifmac and \iflinux.
But we can often use the same text-blocks for mac and linux in our LaTeX file.

Can I use somwhow:
\ifmac OR \iflinux
or can we define a macro such as:
\ifmacORlinux

**Comment by JensTimmerman** [comment]
we currently have an `\ifmacORlinux` macro defined in `style.tex`
