### ISSUE TITLE
Macro's in verbatim mode

### ISSUE THREAD

**Issue by GeertBorstlap** [hpcugent/vsc_user_docs#70]
\userid is not expanded in verbatim mode !!!
"Verbatim mode" prints as is, without expanding any macros. This means that we cannot use a macro in verbatim mode, which we sometimes need! (See example below).

@boegel @gjbex: Any suggestions to avoid this problem?

\begin{verbatim}
Welcome xxx,
* Your vsc-username is %\userid%
* You can view your profile details at https://account.vscentrum.be/req
* For further info please visit https://vscentrum.be/neutral/documentation
Your VSC-admin
\end{verbatim}

**Comment by JensTimmerman** [comment]
this was fixed by ussing `flattext`
