### ISSUE TITLE
Some keywords go in bold in /prompt block

### ISSUE THREAD

**Issue by GeertBorstlap** [hpcugent/vsc_user_docs#71]
Now, the commands inside a prompt block are nicely print in bold. (with the shellcmd macro.)
1) But, several other words in the prompt block are also printed in bold, which is not the intended behavior. (See screenshot attached).  It seems that the "prompt" blocks recognises C-code style keywords of some sort...?
![screen shot 2014-08-21 at 14 16 11](https://cloud.githubusercontent.com/assets/6941436/3995832/2c0fdd8c-292d-11e4-971e-9c5a39cf420c.png)
2) And sometimes the grey background color is broken on one line. This happens mostly after using a macro ... (See screenshot #2 and #3)

@VSC-LaTeX-gurus: Ideas to solve this?

**Comment by boegel** [comment]
@redfast00 Is this still relevant?

**Comment by redfast00** [comment]
No and yes:

- The bash keywords aren't highlighted anymore
- The white background still happens

**Comment by boegel** [comment]
Maybe open a dedicated issue on the latter, since this issue is about two very different things imho...
