### ISSUE TITLE
document webportal relaunch

### ISSUE THREAD

**Issue by stdweird** [hpcugent/vsc_user_docs#722]
See 
![Screenshot 2024-09-17 at 15 48 03](https://github.com/user-attachments/assets/29cf4283-8c1d-4dc3-8448-3b964f1c3fd3)

You can find it under the "My interactive sessions" (the icon on the menu bar)

**Comment by boegel** [comment]
@lbarraga Can you look into adding an extra screenshot and short piece of text for this to the web portal page in the docs?

Better make a new screenshot using `donphan` cluster, the screenshot here was made on Tier-1 Hortense web portal so doesn't make much sense for Tier-2
